### ISSUE TITLE
Error while launching the EDGE VM

### ISSUE THREAD

**Issue by arunkom** [LANL-Bioinformatics/EDGE#10]
Hi 
I've downloaded and tested the md sum for the EDGE VM but cannot get it to launch. Using 2 different VM softwares gives 2 different errors as shown below. Please let me know if you can help with this in case I am doing something wrong.

1. Importing the ova through VirtualBox gives the following error:

Failed to import appliance /Documents/EDGE_vm_RC1.ova.
Error reading "/Users/arunkommadath/Documents/EDGE_vm_RC1.ova": Host resource of type "Other Storage Device (20)" is supported with SATA AHCI controllers only, line 47.

2. Importing the ova through VMWare Fusion gives the following error: "Operating system not found".
![image](https://cloud.githubusercontent.com/assets/12473648/13791077/0bdb129c-eab1-11e5-9190-ef61fc074631.png)

Thanks
Arun

**Comment by poeli** [comment]
Hi Arun,

It seems that you chose to boot from your network at your fusion VM environment according to the screenshot. The error message simply said that no boot file received over your local network. I would suggest you to go to “Settings” and choose to boot from “Hard Disk (SCSI)” under "Startup Disk”. Hope that helps.

Thanks,
Paul

Po-E (Paul) Li
Bioenergy And Biome Sciences (B-11)
Bioscience Division
Los Alamos National Laboratory
Phone:(505) 664-0943
Email: po-e@lanl.gov<mailto:po-e@lanl.gov>

On Mar 15, 2016, at 1:27 PM, arunkom <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi
I've downloaded and tested the md sum for the EDGE VM but cannot get it to launch. Using 2 different VM softwares gives 2 different errors as shown below. Please let me know if you can help with this in case I am doing something wrong.

  1.  Importing the ova through VirtualBox gives the following error:

Failed to import appliance /Documents/EDGE_vm_RC1.ova.
Error reading "/Users/arunkommadath/Documents/EDGE_vm_RC1.ova": Host resource of type "Other Storage Device (20)" is supported with SATA AHCI controllers only, line 47.

  1.  Importing the ova through VMWare Fusion gives the following error: "Operating system not found". [image] <https://cloud.githubusercontent.com/assets/12473648/13791077/0bdb129c-eab1-11e5-9190-ef61fc074631.png>

Thanks
Arun

**Comment by arunkom** [comment]
Thanks Paul.

The fact that I am able to launch other VMs that I created myself in the
past tells me that it could be something you set in your VM that looks to
boot from network. Is that possible that the "boot from your network" is an
option that was set for your VM. I am unable to change it. Tried
recommendations on this issue from various forums without success.

Please advise.
Arun
