### ISSUE TITLE
Free memory calculation on CentOS 7

### ISSUE THREAD

**Issue by donutbrew** [LANL-Bioinformatics/EDGE#15]
The version of the "free" utility on CentOS 7 breaks the function that determines free memory.

In edge_action.cgi (line 1065), 
```
my $mem = `free -m | awk 'NR==3{printf "%.1f", \$3*100/(\$4+\$3)}'`;
```
should be (for CentOS 7):
```
my $mem = `free -m | awk 'NR==2{printf "%.1f", \$7*100/(\$2)}'`;
```
Might be a good idea to do an OS check (or "free" version check) and then use that to autmatically use the right command.

**Comment by chienchi** [comment]
Thanks for the but report. 
The calculation is to determine the used memory percentage instead of free memory. 

We have revisited the memory usage calculation and think the following formula would be compatibale for different OS. 

    my $mem = `vmstat -s | awk  '\$0 ~/total memory/ {total=\$1 } \$0 ~/free memory/ {free=\$1} \$0 ~/buffer memory/ {buffer=\$1} \$0 ~/cache/ {cache=\$1} END{print (total-free-buffer-cache)/total*100}'`;

I have testing it on Ubuntu 14.04 , 16.04 and CentOS 7.2.1511.

**Comment by donutbrew** [comment]
Yes--I got that backwards. The vmstat  way is good (and should be more stable!). It also works on CentOS 6.6. Also, this is Clint.

**Comment by chienchi** [comment]
Got it.  Thanks for testing it on CentOS 6.6.  Clint.  I have push the update at commit 06af7f1a2e93d797e61932a77e0b91e596c26831.
