### ISSUE TITLE
microbial_profiling diamond issue

### ISSUE THREAD

**Issue by donutbrew** [LANL-Bioinformatics/EDGE#21]
Custom DB parameters are not passed through for diamond module. Needs the following modifications:

microbial_profiling_configure.pl:34 
`"diamond=s",  `  to
`"diamond-db=s",   `

microbial_profiling.settings.tmpl:163
`COMMAND=uge-diamond.sh -i %FASTQ% -p %PREFIX% -o %OUTPUT_DIR% -t %THREADS%` to
`COMMAND=uge-diamond.sh -i %FASTQ% -p %PREFIX% -o %OUTPUT_DIR% -t %THREADS% -d <TMPL_VAR NAME="diamond-db">`

**Comment by chienchi** [comment]
Thanks @donutbrew , I have merged the change to dev branch.

commit cbb276d28f4dc5703a81a6b563e75e7aa61fef26
