### ISSUE TITLE
NCBI Genomes vs Taxonomy

### ISSUE THREAD

**Issue by donutbrew** [LANL-Bioinformatics/EDGE#22]
The available  edge_dev_NCBI_genomes.tgz file is out of sync with the current NCBI taxonomy. The  Ref_list.json file is more or less current with the taxonomy, so the problem is when selecting a genome from the selector in the Reference-Based Analysis section, if the name has changed, the genome cannot be found since EDGE located the genome by name in the NCBI_genomes folder. 

in runPipeline, $referenceGenome doesn't get set, so the pipeline quietly skips over that section without an error message. It would be good to have some sort of recorded error if the noted reference cannot be found.

**Comment by donutbrew** [comment]
BTW, the example where I noticed this was for "Middle East Respiratory Syndrome Coronavirus" vs now it's "Middle East Respiratory Syndrome-related Coronavirus." Such an unnecessary change!

**Comment by chienchi** [comment]
I double checked the tall ball and  /edge_ui/data/Ref_list.json in the repo dev branch and they are synced.  But it is good idea to add a check point if the reference file is not there.

**Comment by chienchi** [comment]
I added a check point when the reference db is not synced with ref_list.json. 
commit 21cb35b5dde066c8f8f63ed4903a77729d4d1008
