### ISSUE TITLE
Variable typos in index/edge_config.tmpl (dev)

### ISSUE THREAD

**Issue by donutbrew** [LANL-Bioinformatics/EDGE#24]
Some variables are inconsistent between index.html and edge_config.tmpl. Please see the following on line 104 of edge_config.tmpl --difference of a hyphen vs underscore:

`r2g_consensus_min_cov=<TMPL_VAR NAME=edge-r2g-con-min_cov DEFAULT=5>`
to
`r2g_consensus_min_cov=<TMPL_VAR NAME=edge-r2g-con-min-cov DEFAULT=5>`

There may be others like this. I'll keep a look out.

**Comment by chienchi** [comment]
Thanks! @donutbrew.  The fixed has been pushed to commit ed9bad25566f3667b86684293b2c26ab37c8d8f8
