### ISSUE TITLE
null characters in config.txt

### ISSUE THREAD

**Issue by donutbrew** [LANL-Bioinformatics/EDGE#26]
Null characters are making their way into the "enabledTools=" section of the config.txt file when Taxonmoy Classification is off. It causes runPipeline to die ("Invalid characters detected"). Also causes problems grepping. Can you either take out the conditional on edge_submit.cgi:419 or prevent the enabled tools from ever printing to the config file?

**Comment by chienchi** [comment]
Thank you for the pointing out the bug. I have push the bug fix. 
with commit 884247f0c1dcdd7caebede928063298781a4c5fc
