### ISSUE TITLE
getreadsbytaxa when custom DB is used

### ISSUE THREAD

**Issue by donutbrew** [LANL-Bioinformatics/EDGE#27]
The default database names are hardcoded in the getreadsbytaxa (line~682) section of edge_action.cgi. It will be necessary to read in custom db names from the config file if those are used.

**Comment by donutbrew** [comment]
devel branch

**Comment by chienchi** [comment]
Thanks. It seems affect gottcha2 and pangia mainly. We will figure out the solution. However, if the custom DB doesn't have accession number when created the db or the if the accession is not in the NCBI taxonomy db, the extraction reads capability will break.

**Comment by chienchi** [comment]
commit fa3adc31354f5cc536ff4174bb1e1452543b2d6f
