### ISSUE TITLE
Manual entry for quality score encoding

### ISSUE THREAD

**Issue by mattjmeier** [LANL-Bioinformatics/EDGE#28]
Hello,

I have a sample that kept getting >99% of reads filtered based on quality score, but the read quality is actually ok, it's just that FaQCs is guessing the wrong encoding (it should be 33 but it's guessing 64 for some unknown reason). I was wondering if it would be possible to have an option in the GUI to manually enter the encoding (the ascii flag). In the mean time I will try running this particular sample on the command line.

Thanks,
Matt

**Comment by chienchi** [comment]
Thanks for the suggestion.  We will add this feature for next version or you can pull the update when it is pushed to the repo. I will update this issue tracker when the feature has been added. 

The auto-guessing algorithm used by many other open source tools too and we don't have issue when fastq read came out from different illumina platform. We have a few failed cases reported when the reads are simulated from reads simulator or from other sequencing platform (such as 454). The fastq quality encoding per illumina/sanger defined as shown in the [wikipedia](https://en.wikipedia.org/wiki/FASTQ_format). 

Chienchi

**Comment by chienchi** [comment]
I have pushed the buttons for Phred offset in the GUI in the commit b93e3a5dc49a0db34a532740a45c1

**Comment by mattjmeier** [comment]
Thanks for doing this. By the way - just so you know, it was Ion Torrent data that was causing the issue for me; I've never had a problem with Illumina data.

Cheers,
Matt
