### ISSUE TITLE
How to sync NCBI_Genomes with ref_list.json file?

### ISSUE THREAD

**Issue by mattjmeier** [LANL-Bioinformatics/EDGE#29]
Hello,

I'm attempting to do some reference-based analysis, but I'm getting the error:

`Cannot file genbank for Klebsiella_aerogenes_ASM102199v1. The NCBI_genomes are not be synced with Ref_list.json file.`

However, it seems to work fine with other genomes. I think it could be related to the fact that the folder in the NCBI_genomes database is called _Enterobacter__aerogenes_ASM102199v1, but the dropdown menu in EDGE is looking for Klebsiella_aerogenes_ASM102199v1. I can't actually locate the ref_list.json file.

Any idea what I should do?

Thanks,
Matt

**Comment by chienchi** [comment]
Could you download the database from the ftp site and update the database?

ftp://ftp.lanl.gov/public/genome/EDGE/dev/edge_dev_NCBI_genomes.tgz

Sorry about that, we currently doesn't have the database versioning. It will be better to have versions for the database or date.  The one you have is from 2017 Feb. We have the database update on 2017 Oct.

**Comment by mattjmeier** [comment]
Thanks for the quick reply. I will update my database.

Matt
