### ISSUE TITLE
Syntax for batch submissions with multiple single end files

### ISSUE THREAD

**Issue by mattjmeier** [LANL-Bioinformatics/EDGE#30]
Hello,

Sorry if this is already documented somewhere, but I was wondering if there is a way to create batch submissions using single-end data with multiple FASTQs per sample. I can just concatenate them of course - but I would prefer to avoid the overhead if it's possible. I have tried adding multiple columns (S1, S2, S3, etc) and also using 1 column with all files listed comma separated, but no luck.

Thanks,
Matt

**Comment by chienchi** [comment]
The current version doesn't allow multiple single end files for batch submission.  I think it is a good idea and an enhancement feature. I will add the function into codes. 

Thanks.

**Comment by chienchi** [comment]
I have push the update with commit 85039c7b5face91e7630228d256ce45b9fe745ce. 

The multiple single end reads files can be input as comma-separated in the batch description file with column header "S".
