### ISSUE TITLE
Data migration during updates in docker

### ISSUE THREAD

**Issue by mattjmeier** [LANL-Bioinformatics/EDGE#31]
I was hoping you could provide some information on how to best perform updates to the docker image.

I followed this basic scheme to grab your latest update:

```
docker pull bioedge/edge_dev
docker stop edge
docker rm edge
docker run edge
```

(Where the "docker run edge" command included the full parameters to run the container as I've done previously). After the latest update I can't see the projects I ran previously (although I can see that their directories are intact in the EDGE_output folder). Is there a way to import the previous database? Could my problem be related to permissions/ownership?

Thanks,
Matt

**Comment by mattjmeier** [comment]
I just wanted to add to this: I had to roll back to the previous image (I'm running 2.1.1). I have no idea if it's actually a bug or something wrong with the way I updated though... the problem could very well be on my end.

Unfortunately I had to roll back because I found that 2.3.0 not only didn't see my previous database, but also couldn't create new projects.

Running 2.1.1 everything seems back to normal (database of old projects present, new projects start properly). Let me know if there is anything you'd like me to do to troubleshoot!

Thanks for all your help.

Matt

**Comment by chienchi** [comment]
I think it is a bug in the docker image because of the database schema update in 2.3.0.  We added two new columns in the projects table of the mysql database (to speed up projects page display) but the docker database volume created by the user end does not have the two new columns (run_submitted and running_time).  

It can be check by command:
 $ docker exec edge /bin/bash -c "mysql -f -u edge -pedge -D userManagement -e 'desc projects;'"

To fix this, after docker container is up (docker run), please apply the following command:

 $ docker exec edge /bin/bash -c "mysql -f -u edge -pedge -D userManagement < /edge_source/userManagement/update_userManagement_db.sql 2>/dev/null"

**Comment by chienchi** [comment]
Hi,

I have push the fix to the latest docker image (bioedge/edge_dev:latest).  Could you try pull the new update?  Let me know how it goes. 

Thanks.

**Comment by mattjmeier** [comment]
Hello,

I pulled the latest version and the reports are now available under the project list! Thank you so much for your quick help.

As a side note, I'm not sure if it's by design, but the projects don't automatically appear in the sidebar until I click on one of them from the project list page. Also, the new columns (submission time and running time) only get populated with data once they have been clicked. Not a problem for me, I just thought you might like to know this.

Thanks again!
Matt

**Comment by mattjmeier** [comment]
Oh... I also noticed some other funny behavior, it seems that "deleted" projects and "in progress" projects are listed in the projects screen now. Thought you might also want to know that, if it's not intentional.

**Comment by chienchi** [comment]
Thanks for the information.  The database should be clean up for the update in the future.  We will think about a way to clean up/update for existing projects automatically. Right now, the 'in progress' and submission time and running time of existing projects will be updated when users click on project report. 

For the delete projects, the following command is to clean up the database

$ docker exec edge /bin/bash -c "mysql -f -u edge -pedge -D userManagement -e \"delete from users_projects where project_id in (select id from projects where status='delete'); delete from projects where status='delete';\""
