### ISSUE TITLE
Question: How did you created the UI?

### ISSUE THREAD

**Issue by hieplpvip** [LANL-Bioinformatics/EDGE#33]
Hello,

Currently I'm building a pipeline for Helicobacter pylori. It will run online and have UI. However, I don't know how to create the UI. Could you share me how you did it?

Thanks,
Hiep Le.

**Comment by chienchi** [comment]
Hi,

Thanks for interesting the UI of EDGE.  You may check out the UI component in edge_ui directory in the github repo. It uses the JQUERY Mobile framework  (https://jquerymobile.com/) to design the UI.   However, JQuery seems not update for a while and there are other more popular UI framework you can check out. They are also much bigger community which you can get more question answered if possible. Such as React, Angular etc.

Chienchi
