### ISSUE TITLE
"Ready to Submit" button is not always present in results page

### ISSUE THREAD

**Issue by mshakya** [LANL-Bioinformatics/EDGE#37]
I ran some nanopore samples (SRR11313280 and SRR11313494) through edge-covid19. In the results page, there was no "Ready to Submit" column. They had really low coverage and lots of Ns. However, when I ran an Illumina sample with decent coverage, it did show up. I am not sure if its nanopore specific or it just doesn't show up if the consensus genome threshold is not met. I think it should show up regardless, and if it doesnt meet the threshold maybe we add a red X instead of green check mark.

**Comment by mshakya** [comment]
Update: another nanopore project just finished and this time there is "Ready to Submit" column and has a green check mark.

**Comment by chienchi** [comment]
It is intend behavior.  Only project pass the criteria will show the column and button, no matter what sequencing platform.
