### ISSUE TITLE
EDGE-COVID19: In the results page, variant analysis always shows as "Auto"

### ISSUE THREAD

**Issue by mshakya** [LANL-Bioinformatics/EDGE#43]
In the results page, in `General` tab, Variant analysis option is always set to Auto, even when its turned ON. Maybe make it ON/OFF and not show up as Auto.

**Comment by chienchi** [comment]
Variant call is different variant analysis.  Variants analysis is to see what genes affects by variants or gaps.

**Comment by mshakya** [comment]
hmm...ok, maybe also add variant call row?

**Comment by chienchi** [comment]
It is part of reference based analysis and not a separate module in the pipeliene.  So, if variant call been used, it will show the SNP/INDEL in the result page.
