### ISSUE TITLE
Show more relevant information in My Project List

### ISSUE THREAD

**Issue by mshakya** [LANL-Bioinformatics/EDGE#44]
Add more columns. Some columns to add are `sequencing platform or `Nanopore (Yes/No)`. Maybe some results like number of reads, adding others might be complicated.

**Comment by chienchi** [comment]
commit [#81d486](https://github.com/LANL-Bioinformatics/EDGE/commit/81d486e829d6023ef0d8f5c32abcacb6562acce7)
