### ISSUE TITLE
add google analytics

### ISSUE THREAD

**Issue by mflynn-lanl** [LANL-Bioinformatics/EDGE#49]
We will add google analytics to the index.html file to track website usage

**Comment by mflynn-lanl** [comment]
google analytics is already in the landing page index.html and the assay_validation subdomain. We will need to add it to the subdomains, edge-covid19, survey-page and edge. I can add it to the survey_page since that's local to our project, but edge-covid19 and edge images are public. We don't want to add our google analytics account to those images. We will need to figure out how to add google analytics to these containers automatically when they are created.

**Comment by chienchi** [comment]
Transparent, open source alternative to Google Analytics
https://opensource.com/article/20/5/plausible-analytics
