### ISSUE TITLE
Inconsistent project name

### ISSUE THREAD

**Issue by poeli** [LANL-Bioinformatics/EDGE#50]
**Describe the bug**

Project name shown on the project list at the left side bar is not what's sown in the project report.

**To Reproduce**
0. after a run has been submitted successfully
1. Go to 'Rename project'
2. Leave project name empty and click 'Comfirm'
3. You will see the project name is shown as project ID at the project list
4. Go to 'Rename project'
5. Change project name to 'RaTG13_1'
6. The name in the project report changed but not at the project list.

**Expected behavior**
Project names should match each other.

**Screenshots**

![image](https://user-images.githubusercontent.com/7082539/80235186-9840af80-8616-11ea-9e1b-e992d04864ac.png)

**Comment by chienchi** [comment]
Thanks for the detailed bug report with screenshot.   Best bug reporter I have seen.   
I have fixed it.  Thank you.

**Comment by poeli** [comment]
My pleasure. Best fixer ever!
