### ISSUE TITLE
batch project submission skips projects if the name is repeated in the batch file

### ISSUE THREAD

**Issue by aretchless** [LANL-Bioinformatics/EDGE#55]
**Describe the bug**
When using the 'batch project submission' option on the "Run Edge" page, we noticed that the number of submitted projects was less than described in the excel file. This was due to apparent deduplication of the excel file based on project name. When a name is listed twice in the excel file, the second one is retained and the first one dropped (silently).

**To Reproduce**
We are using an in-house instance with v2.4 installed . I don't see a convenient way to replicate on https://edgebioinformatics.org/

**Expected behavior**
Either run both projects (as would happen if they had been submitted separately with the same name), or reject the batch file with an error message, or deduplicate the file with a notification that one project has been dropped.

This is low priority.

**Comment by chienchi** [comment]
checking duplicate project name implemented for batch submit #[commit 5f3f09cf](https://github.com/LANL-Bioinformatics/EDGE/commit/5f3f09c2dd8170f2b6f0e84e653617b569c898ff)
