### ISSUE TITLE
Feature request: Include project name when extracting reads mapped to reference

### ISSUE THREAD

**Issue by aretchless** [LANL-Bioinformatics/EDGE#56]
**Describe the bug**
When retrieving reads mapped to reference from the website, the FASTQ files are labeled only with the reference name and not the project name. It would be easier to work with these files if they included the project name also (as the zip file does).

**To Reproduce**
1. Run EDGE with reference based analysis
2. Go to the results section describing how many reads mapped to each record in the fasta file (see image below, showing page from a recently run project with code https://edgebioinformatics.org/?proj=e0df5123e673e5d1728bd9253af755cb ).
3. Click on the value in the "mapped reads" column to get a zipped folder containing three FASTQ files.
4. The Zip file has a fully descriptive name (project and reference, such as "AU_ILMN_Unhyb_v13_reftest_HMPV__NC_004148_2.mapped.fastq".
5. However, the individual filenames only include the reference, such as "HMPV__NC_004148.2.mapped.1.fastq"

**Expected behavior**
Filenames are like the folder name, e.g. AU_ILMN_Unhyb_v13_reftest_HMPV__NC_004148_2.mapped.1.fastq

**Screenshots**

![image](https://user-images.githubusercontent.com/50489999/204908839-52fe37d8-45e7-4850-9ae2-c86fc7a1a8c7.png)

**Comment by chienchi** [comment]
checkout #[commit688f721](https://github.com/LANL-Bioinformatics/EDGE/commit/688f7214a703ccda3f5f56d4c67ca2608956c83b)
