### ISSUE TITLE
Does command-line submission bypass the queue system on EDGE?

### ISSUE THREAD

**Issue by aretchless** [LANL-Bioinformatics/EDGE#57]
Hello @chienchi et al. This is a question rather than a bug.

I am thinking of using EDGE command line tool to automate run analysis and to run datasets for testing purpose.  This uses the 'runPipeline' command. My understanding is that this command occurs downstream of the queue that is created during batch submission from the GUI. 

In that case, it would be up to my submission scripts to monitor resource availability and control how many jobs are running at once. Is that correct?

thanks

**Comment by chienchi** [comment]
It is correct. The runPipeline command is the main workflow execution script. The resource is monitored by the front-end javascript plus the server side cgi scripts.   We also use command line version 'runPipeline' locally for large batch runs and testing purpose too and the jobs can be submitted to cluster. So, cluster scheduler can help us monitor the job resource usage.

**Comment by aretchless** [comment]
Thanks for the answer. And thanks for inviting me to the discussions forum.
