### ISSUE TITLE
Site-generated emails are not received by gmail users

### ISSUE THREAD

**Issue by mflynn-lanl** [LANL-Bioinformatics/EDGE#60]
Site-generated emails with the activation link aren't being received by users with gmail accounts for edgebioinformatics.org and edge-covid19.edgebioinformatics.org 
I've gotten 4 requests to activate accounts for gmail users because they didn't receive the activation link
I just created a new yahoo account and I received the email link
tried resetting one of my gmail accounts and I haven't received a link, neither in my main email folder nor my spam folder.
This may be because of our DNS settings for the domains 
https://support.google.com/mail/answer/81126?hl=en

**Comment by mflynn-lanl** [comment]
I did not have this problem setting up a new account on nmdc-edge.org with a gmail account

**Comment by yxu-lanl** [comment]
Could you change the 'email_sender' setting in the sys.properties to edge lanl email?
```java
String from = this.getSetting("email_sender");
		String host = this.getSetting("email_host");

		if (this.getSetting("email_host").equals("localhost")) {
			String sendmailScript = this.getSetting("sendmail_script");
			subject = subject.replaceAll("'", "\"'\"");
			text= text.replaceAll("'", "\"'\"");
			String cmd = sendmailScript + " -from '" + from + "' -to '" + to + "' -subject '" + subject + "' -message '" + text +"'";
			execCmd(cmd);
			
		}
```
