### ISSUE TITLE
Can't connect to database

### ISSUE THREAD

**Issue by Stopi** [LANL-Bioinformatics/EDGE#62]
**Describe the bug**
After upgrading docker-desktop to last version, I lost access to EDGE.
I've opened a terminal and tried to see the logs from apache
```
tail -f /var/log/apache2/error.log
```
Whenever I refresh the page on my browser (http://localhost), I see this:
```
Can't connect to database: Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock'
```

When trying to connect to mysql directly from the terminal, I got the same issue:
```
sh-4.4# mysql -f -u edge -pedge -D userManagement -e 'desc projects;'
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
```
The socket file exists but seems to not have been modified since before the docker-desktop upgrade.

**To Reproduce**
Not sure if you can reproduce that, nor how.

**Expected behavior**
I expect mysql to come back, so that I can access my data.
Maybe someone can give me instruction to follow for troubleshooting this.
I'm not a java/tomcat expert by I know mysql & apache very well, and I'm comfortable with using a shell.

**Screenshots**
- none -

**Desktop (please complete the following information):**
 - OS: Windows 10 + WSL 2
 - Browser is Firefox, last version (but that's irrelevant)
 - EDGE Version: v2.4.0 build 20230412

**Additional context**
I also tried to create new containers with official instructions (https://hub.docker.com/r/bioedge/edge-covid19) but even tho, the problem persist in that new container.
```
docker create --name mysql_data2 --volume /var/lib/mysql  bioedge/edge_ubuntu_mysql
docker run -d --volumes-from mysql_data2  \
-v $PWD/EDGE_output:/home/edge/EDGE_output \
-v $PWD/EDGE_input:/home/edge/EDGE_input \
-v $PWD/EDGE_report:/home/edge/EDGE_report \
-v $PWD/human_ref_GRCh38_all.fa.gz:/home/edge/edge/database/human_ref_GRCh38_all.fa.gz \
-p 80:80 -p 8080:8080 --name edge_ncov2 bioedge/edge-covid19
```

**Comment by chienchi** [comment]
I cannot reproduce the error you have by using Docker Desktop 4.21.1 in Windows 11.  The mysql or tomcat error message may help with resolving the issue.

The mysql status in container can be checked by command:
    `$ docker exec edge_ncov2 service mysql status`
where "edge_ncov2" is the container name when user docker run it with --name flag

And user management system service status:
    `$ docker exec edge_ncov2 service tomcat7 status`

**Comment by Stopi** [comment]
Hi, thanks for your answer.

```
sh-4.4# service tomcat7
Run as /etc/init.d/tomcat7

sh-4.4# service mysql status
 * MySQL is stopped.

sh-4.4# service mysql start
 * /etc/init.d/mysql: ERROR: The partition with /var/lib/mysql is too full!

sh-4.4# df -h /var/lib/mysql
Filesystem      Size  Used Avail Use% Mounted on
/dev/sdd        251G  240G     0 100% /var/lib/mysql
```
So apparently this is a disk space issue.

I investigated and realized I made a mistake in the command line when creating the container.
So all edge's output were not on a mounted folder outside the container but instead were contributing to make the vdisk image growing everyday.

I fixed that.
