### ISSUE TITLE
Use of `./` in output path breaks several scripts

### ISSUE THREAD

**Issue by ar0ch** [LANL-Bioinformatics/EDGE#8]
A minor issue, running the pipeline using the below command or any iteration that uses the './path/to/' syntax in the outDir option results in a few of the perl scripts bailing out. Particularly contig_stats and contig_classifier_by_bwa (possibly others, I didn't keep stepping through the pipeline).

`runPipeline2 -c bgt11.conf -p ~/trimmed/BGT11_S11_L001_R1_001.trimmed.fastq.gz ~/trimmed/BGT11_S11_L001_R2_001.trimmed.fastq.gz -o ./bgt11`

I'm guessing there's an issue somewhere in the string passing that's going on with executeCommand because despite all the variables filling fine, e.g. contig_stats errors out:

> the command perl /home/achande3/staging/EDGE/scripts/contig_stats.pl -p ./bgt112/AssemblyBasedAnalysis/contigs.fa > contigs_stats.txt failed

However the command as listed in the error functions correctly if run interactively:

>  perl /home/achande3/staging/EDGE/scripts/contig_stats.pl -p ./bgt112/AssemblyBasedAnalysis/contigs.fa
> File    Contigs_number  N50     N90     Max     Min     Mean    Median  Total_bases     Top10_bases     Top20_bases     Top40_bases     Top100_bases    >100kb_bases       >50kb_bases     >25kb_bases     >10kb_bases     >5kb_bases      >3kb_bases      >2kb_bases      >1kb_bases
>     285     120088  200     346262  200     13838   680     3943967 1915344 2871728 3653427 3852222 2375296 3182746    3563440 3722601 3755680 3772324 3806884 3861063

Replacing `./` with `$PWD` or not prefixing solves the issue

I've also attached the conf file I'm using just in case
[bgt11.conf.txt](https://github.com/LANL-Bioinformatics/EDGE/files/143066/bgt11.conf.txt)

**Comment by chienchi** [comment]
Thanks for the bug report. If job submit through GUI, it always use absolute path such that we didn't find the bug before. The commit [#64a9618](https://github.com/LANL-Bioinformatics/EDGE/commit/64a9618b76a15764021b420f49c34de635c80611) should fix the bug.

**Comment by ar0ch** [comment]
I can confirm that 64a9618b76a15764021b420f49c34de635c80611 fixes the issue. Thanks for fixing so quickly
